// import React from 'react'

const UseServices = () => {
  return (
    <div className="bg-gray-50 min-h-screen py-12 px-6 lg:px-24">
      <div className="max-w-5xl mx-auto space-y-10">
        {/* Hero Section */}
        <header className="text-center">
          <h1 className="text-4xl md:text-5xl font-extrabold text-gray-900 mb-4">
            Terms of Use / Service – Supernpro.com
          </h1>
          {/* <p className="text-lg text-gray-600 max-w-3xl mx-auto leading-relaxed">
            Please read these terms carefully. Your acceptance of the terms
            contained herein constitutes the agreement between you and
            <span className="font-semibold"> MVM Business Services</span> for
            use of Supernpro.com.
          </p> */}
        </header>

        {/* Section Wrapper */}
        <div className="bg-white shadow-md rounded-2xl p-8 space-y-8">
          {/* Intro */}
          <section className="text-gray-600 leading-relaxed">
            <p>
              This Agreement sets forth the terms and conditions that apply to
              the access and use of the website{" "}
              <strong>"Supernpro.com",</strong> incorporated under the laws of
              India and registered under the Companies Act, 1956.
            </p>
            <p className="mt-4">
              This document/agreement (referred to as “Agreement”) is an
              electronic record in terms of the Information Technology Act,
              2000, generated by a computer system and does not require any
              physical or digital signatures. This document is published in
              accordance with the provisions of Rule 3 of the Information
              Technology (Intermediaries Guidelines) 2011, which provides for
              the due diligence to be exercised for the access or usage of this
              website.
            </p>
            <p className="mt-4">
              By accessing this website or registering your information on the
              website, the users (hereinafter referred to as "you" or "your")
              agree to be bound by these Terms of Use ("TOU"). This Agreement,
              along with the Privacy Policy and Disclaimer, describes our
              relationship with you and will be subject to the rules,
              guidelines, policies, terms, and conditions applicable to any
              specific service that is provided by this website, and they shall
              be deemed to be incorporated into this TOU and shall be considered
              as part and parcel of this TOU.
            </p>
            <p className="mt-4">
              Be sure to return to this page periodically to review the most
              current version of the TOU. We reserve the right at any time, at
              our sole discretion, to change or otherwise modify the TOU without
              prior notice, and your continued access to or use of this website
              signifies your acceptance of the updated or modified the TOU
            </p>

            <p className="mt-4">
              PLEASE READ THESE TERMS AND CONDITIONS CAREFULLY. YOUR ACCEPTANCE
              OF TERMS CONTAINED HEREIN CONSTITUTES THE AGREEMENT BETWEEN YOU
              AND THE COMPANY FOR THE PURPOSE AS DEFINED HEREUNDER.
            </p>
          </section>

          {/* Terms Sections */}
          {[
            {
              title: "1. Description and Acceptance of Services",
              content: (
                <>
                  <p>
                    The company hereby offers you access to information
                    primarily about certain products & services, including, but
                    not restricted to, product/services such as news blogs of
                    categories like Health, Technology, Education, Travel,
                    Sports, Fashion, Food, etc. We work with brands to advertise
                    their products & services on our platform. The
                    above-mentioned services are provided on a commercially
                    reasonable effort basis, and you agree that your
                    participation in availing the above-mentioned services is
                    purely at your will and consent.
                  </p>

                  <p className="mt-4">
                    Your continued usage of the Services from time to time would
                    also constitute acceptance of the TOU, including any
                    updation or modification thereof, and you would be bound by
                    this Agreement until this Agreement is terminated as per the
                    provisions defined herein.
                  </p>

                  <p className="mt-4">
                    You agree to receive communications through emails,
                    telephone and/or SMS, from the company or its third-party
                    vendors/business partners/ marketing affiliates regarding
                    the service updates, information/promotional emails and/or
                    product announcements. In this context, you agree and
                    consent to receive all communications at the mobile number
                    provided by you, even if this mobile number is registered
                    under the DND/NCPR list under TRAI regulations.
                  </p>

                  <p className="mt-4">
                    The company will retain and use your information as
                    necessary to comply with our legal obligations, resolve
                    disputes and enforce our agreements entered into for
                    providing services and ancillary services.
                  </p>
                </>
              ),
            },
            {
              title: "2. License and Website Access",
              content: (
                <>
                  <p>
                    The company hereby offers you access to information
                    primarily about certain products & services, including, but
                    not restricted to, product/services such as news blogs of
                    categories like Health, Technology, Education, Travel,
                    Sports, Fashion, Food, etc. We work with brands to advertise
                    their products & services on our platform. The
                    above-mentioned services are provided on a commercially
                    reasonable effort basis, and you agree that your
                    participation in availing the above-mentioned services is
                    purely at your will and consent.
                  </p>

                  <p className="mt-4">
                    Your continued usage of the Services from time to time would
                    also constitute acceptance of the TOU, including any
                    updation or modification thereof, and you would be bound by
                    this Agreement until this Agreement is terminated as per the
                    provisions defined herein.
                  </p>

                  <p className="mt-4">
                    You agree to receive communications through emails,
                    telephone and/or SMS, from the company or its third-party
                    vendors/business partners/ marketing affiliates regarding
                    the service updates, information/promotional emails and/or
                    product announcements. In this context, you agree and
                    consent to receive all communications at the mobile number
                    provided by you, even if this mobile number is registered
                    under the DND/NCPR list under TRAI regulations.
                  </p>

                  <p className="mt-4">
                    The company will retain and use your information as
                    necessary to comply with our legal obligations, resolve
                    disputes and enforce our agreements entered into for
                    providing services and ancillary services.
                  </p>
                </>
              ),
            },
            {
              title: "3. Privacy Policy",
              content: (
                <>
                  <p>
                    By using the website, you hereby consent to the use of your
                    information as we have outlined in our privacy policy. This
                    privacy policy explains how the company treats your personal
                    information when you access the website.
                  </p>
                </>
              ),
            },
            {
              title: "4. Your Registration/Account",
              content: (
                <>
                  <p>
                    In consideration of your use of the Website and registering
                    with us, you represent that you are of legal age to form a
                    binding contract and are not a person barred from receiving
                    services under the laws of India or other applicable
                    jurisdictions and will only use the Website to make
                    legitimate purchases for you or for another person for whom
                    you are legally authorised to act (and will inform such
                    other persons about the TOU and/or Privacy Policy) that
                    apply to the purchase you have made on their behalf
                    (including all rules and restrictions applicable thereto).
                  </p>

                  <p className="mt-4">
                    You agree and understand that you are solely responsible for
                    maintaining the confidentiality of your password, which,
                    together with your login ID (as may be applicable under the
                    service selected), allows you to access the service. That
                    login ID and password, together with any mobile number or
                    other contact information you provide, form your
                    "Registration Information." You agree that you are
                    responsible for maintaining the confidentiality of your
                    login ID and password and for restricting access to your
                    computer. You agree to accept responsibility for all
                    activities that occur through your account or password.
                    Because of this, we strongly recommend that you exit/log out
                    of your account at the end of each session. You agree to
                    notify the company immediately of any unauthorised use of
                    your account or any other breach of security. You further
                    agree that the company shall not be liable for any
                    unauthorised use or access unless it is proved that the
                    unauthorised use or access occurred solely due to reasons
                    directly attributable to the company.
                  </p>

                  <p className="mt-4">
                    You shall provide true, accurate, current, and complete
                    information about yourself and undertake to inform/update of
                    any change in your Registration Information promptly and
                    keep it up-to-date and accurate at all times, as it has a
                    direct bearing on the provision of services through the
                    company. You agree not to misrepresent your identity, nor
                    will you attempt to gain an unlawful access to the website
                    or use of the services. Additional terms and conditions will
                    apply to your purchase of services that you select. Please
                    read these additional terms and conditions carefully.
                  </p>
                </>
              ),
            },
            {
              title: "5. Eligibility",
              content: (
                <p>
                  You declare and confirm that you are a resident of India,
                  above 18 (eighteen) years of age, and have the capacity to
                  contract as specified under the Indian Contract Act, 1872,
                  while availing the services offered by the company.
                </p>
              ),
            },
            {
              title: "6. Third-Party Links Offered",
              content: (
                <>
                  <p>
                    This website may provide links to other websites or
                    resources. Since the company has no control over such
                    third-party websites and resources, you acknowledge and
                    agree that the company is not responsible for the
                    availability of such external sites or resources and does
                    not endorse and is not responsible or liable for any
                    content, advertising, products or other materials on or
                    available from such sites or resources. You further
                    acknowledge and agree that the company shall not be
                    responsible or liable, directly or indirectly, for any
                    damage or loss caused or alleged to be caused by or in
                    connection with the use of or reliance on any such content,
                    goods, or services available on or through any such site or
                    resource.
                  </p>

                  <p className="mt-4">
                    Your interaction with any third party accessed through the
                    website is at your own risk, and the company will have no
                    liability with respect to the acts, omissions, errors,
                    representations, warranties, breaches, or negligence of any
                    such third parties or for any personal injuries, death,
                    property damage, or other damages or expenses resulting from
                    your interactions with the third parties.
                  </p>
                </>
              ),
            },
            {
              title: "7. Disclaimer of Warranty",
              content: (
                <>
                  <p>
                    You expressly understand and agree that your use of the
                    Services and all information, products, other services, and
                    other content (including that of the third parties) included
                    in or accessible from the Website is at your sole risk. The
                    services are provided on an "as is" and "as available"
                    basis. The company makes no representations, warranties, or
                    guarantees, express or implied, regarding the accuracy,
                    reliability, or completeness of the content on the website
                    or of the services (whether or not sponsored by third-party
                    service providers) and expressly disclaims any warranties of
                    non-infringement or fitness for a particular purpose.
                  </p>

                  <p className="mt-4">
                    The company expressly disclaims all warranties of any kind
                    as to the services and all information, products, services,
                    and other content (including that of the third parties)
                    included in or accessible from the services, whether express
                    or implied, including but not limited to the implied
                    warranties of merchantability, fitness for a particular
                    purpose, and non-infringement.
                  </p>

                  <p className="mt-4">
                    The company and its service providers, affiliates, and
                    business partners make no warranty that (i) the services
                    will meet your requirements, (ii) the services will be
                    uninterrupted, timely, secure, or error-free, (iii) the
                    results that may be obtained from the use of the services
                    will be accurate or reliable, (iv) the quality of any
                    products, services, information, or other material purchased
                    or obtained by you through the services will meet your
                    expectations, and (v) any errors in the technology will be
                    corrected.
                  </p>

                  <p className="mt-4">
                    The company does not charge any registration/membership, or
                    browsing fees. However, the company reserves the absolute
                    right to charge any fee for registration/membership or
                    browsing fee at any time. All such fees that the Company may
                    charge will be intimated to the users, and such change shall
                    automatically become effective immediately after they are
                    posted on the website. All such fees charged by the company
                    shall be in Indian Rupees. Your continued use of the company
                    shall be deemed as an acceptance of the amended terms of the
                    TOU.
                  </p>
                </>
              ),
            },
            {
              title: "8. Limitation of Liability",
              content: (
                <>
                  <p>
                    You expressly understand and agree that the Company
                    (including its subsidiaries, affiliates, directors,
                    officers, employees, representatives and providers) shall
                    not be liable for any direct, indirect, incidental, special,
                    consequential or exemplary damages, including but not
                    limited to damages for loss of profits, opportunity,
                    goodwill, use, data or other intangible losses, even if
                    Company has been advised of the possibility of such damages,
                    resulting from (i) any failure or delay (including without
                    limitation the use of or inability to use any component of
                    the Website), or (ii) any use of the Website or content, or
                    (iii) the performance or non-performance by us or any
                    provider, even if we have been advised of the possibility of
                    damages to such parties or any other party, or (b) any
                    damages to or viruses that may infect your computer
                    equipment or other property as the result of your access to
                    the Website or your downloading of any content from the
                    Website.
                  </p>

                  <p className="mt-4">
                    Notwithstanding the above, if the Company is found liable
                    for any proven and actual loss or damage that arises out of
                    or is in any way connected with any of the occurrences
                    described above, then you agree that the liability of the
                    company shall be restricted to, in the aggregate, any
                    service/transactional fees paid by you to the company in
                    connection with such transaction(s)/services on this
                    website, if applicable.
                  </p>

                  <p className="mt-4">
                    The company has no control over the third-party websites
                    that would be provided to you through its website. You
                    acknowledge and agree that under no circumstances shall the
                    Company be liable for your use of the services offered or
                    provided by any third-party service provider.
                  </p>
                </>
              ),
            },
            {
              title: "9. Site-Provided Email and Postings",
              content: (
                <>
                  <p>
                    The Site / Mobile Application may provide users with the
                    ability to send email messages to other users and non-users
                    and to post messages on the Site/Mobile Application.
                    Supernpro.com is under no obligation to review any messages,
                    information, or content ("Postings") posted on the
                    Site/Mobile Application by users and assumes no
                    responsibility or liability relating to any such Postings.
                    Notwithstanding the above, Supernpro.com may from time to
                    time monitor the postings on the site/mobile application and
                    may decline to accept and/or remove any email or postings.
                  </p>

                  <p className="mt-4">
                    You understand and agree that you shall not use any
                    functionality provided by the Site / Mobile Application to
                    post content or initiate communications or host, display,
                    upload, modify, publish, transmit, store, update, or share
                    any information that contains: (i) any unlawful, harmful,
                    threatening, abusive, harassing, defamatory, vulgar,
                    obscene, profane, hateful, racially, ethnically, or
                    otherwise objectionable material of any kind, including but
                    not limited to material which encourages conduct that would
                    constitute a criminal offense, give rise to civil liability
                    or otherwise violate any applicable local, state, national,
                    or international law, or is defamatory, obscene,
                    pornographic, paedophilic, invasive of another's privacy
                    including bodily privacy, insulting or harassing on the
                    basis of gender, libellous, racially or ethnically
                    objectionable, relating to or encouraging money laundering
                    or gambling, or otherwise inconsistent with or contrary to
                    the laws in force; (ii) advertisements or solicitations of
                    any kind; (iii) impersonation of others or providing false
                    information or information belonging to another person
                    without rights; (iv) personal information such as messages
                    stating phone numbers, account numbers, addresses, or
                    employer references; (v) messages by non-spokesperson
                    employees of Supernpro.com, purporting to speak on behalf of
                    Supernpro.com or containing confidential information or
                    opinions concerning Supernpro.com; (vi) messages offering
                    unauthorized downloads of copyrighted or private information
                    or infringing any patent, trademark, copyright, or other
                    proprietary rights; (vii) multiple messages placed within
                    individual folders by the same user restating the same
                    point; (viii) chain letters of any kind; (ix) identical (or
                    substantially similar) messages to multiple recipients
                    advertising any product or service, expressing a political
                    or other similar message, or any other type of unsolicited
                    commercial message; (x) content harmful to children; (xi)
                    content that deceives or misleads the addressee about the
                    origin of the message or knowingly communicates patently
                    false or misleading information; (xii) impersonation of
                    another person; (xiii) threats to the unity, integrity,
                    defence, security, or sovereignty of India, friendly
                    relations with foreign States, or public order, or
                    incitement to commit any cognisable offence; (xiv) software
                    viruses or other code designed to interrupt, destroy, or
                    limit the functionality of any computer resource; or (xv)
                    content written or published to mislead or harass a person,
                    entity, or agency for financial gain or to cause injury to
                    any person.
                  </p>
                </>
              ),
            },
            {
              title: "10. Indemnity",
              content: (
                <>
                  <p>
                    You agree to indemnify and hold the company (and its
                    affiliates, officers, directors, agents, and employees)
                    harmless from any and against any claims, causes of action,
                    demands, recoveries, losses, damages, fines, penalties, or
                    other costs or expenses of any kind or nature, including
                    reasonable attorneys' fees, or arising out of or related to
                    your breach of this TOU, your violation of any law or the
                    rights of a third party, or your use of the website.
                  </p>

                  <p className="mt-4">
                    You shall not sue or otherwise make or present any demand or
                    claim, and irrevocably, unconditionally, and entirely
                    release, waive, and forever discharge the Company, its
                    officers, directors, employees, agents, licensees,
                    affiliates, successors, and assigns, jointly and
                    individually (hereinafter "Release"), from any and all
                    manner of liabilities, claims, demands, losses, claims,
                    suits, costs, and expenses (including court costs and
                    reasonable attorney fees) ("Losses"), whatsoever, in law or
                    equity, whether known or unknown, that you ever had, now
                    have, or in the future may have against the Release with
                    respect to the Services. You agree to defend, indemnify, and
                    hold harmless the Release from and against any and all
                    losses resulting from claims made against the company by
                    third parties arising from and in connection with this
                    authorisation.
                  </p>
                </>
              ),
            },
            {
              title: "11. Additional Terms and Conditions",
              content: (
                <>
                  <p>
                    The company reserves the right to make changes to the
                    website, related policies and agreements, this TOU and the
                    privacy policy at any time as it deems fit and proper,
                    including but not limited to complying with changes in law
                    or regulation, correcting inaccuracies, omissions, errors,
                    or ambiguities, reflecting changes in the process flow,
                    scope, and nature of the services and ancillary services,
                    company reorganisation, market practice, or customer
                    requirements. Upon any change, the company will notify you
                    of the updated terms on the website or by other means. Your
                    continued use of the Services constitutes acceptance of the
                    changes and an agreement to be bound by the Terms, as
                    amended. If you do not agree to the changes, you may please
                    discontinue your use of the Services.
                  </p>

                  <p className="mt-4">
                    The company reserves the right to discontinue or suspend,
                    temporarily or permanently, the services, including
                    ancillary services, by giving reasonable time period notice,
                    on a best-effort basis, unless it is merely to change
                    certain features/contents of the services and/or website or
                    maintain the security and integrity of the services. You
                    agree that the company will not be liable to you in any
                    manner whatsoever for any modification or discontinuance of
                    the services.
                  </p>

                  <p className="mt-4">
                    You agree not to use the Services and ancillary services for
                    illegal purposes or for the transmission of material that is
                    unlawful, harassing, libellous (untrue and damaging to
                    others), invasive of another's privacy, abusive,
                    threatening, or obscene, or that infringes the rights of
                    others.
                  </p>

                  <p className="mt-4">
                    The company may, from time to time, announce certain offers
                    with the intent to promote its website and/or
                    Services/ancillary services ("Promotional Offer/s"). The
                    Promotional Offer(s) would always be governed by this TOU
                    plus certain additional terms and conditions, if any are
                    prescribed. The said additional terms and conditions, if
                    prescribed, would be specific to the corresponding
                    Promotional Offer only and shall prevail over these TOU, to
                    the extent they may be in conflict with these Terms. The
                    company reserves the right to withdraw, discontinue, modify,
                    extend and suspend the Promotional Offer(s) and the terms
                    governing it at its sole discretion.
                  </p>
                </>
              ),
            },
          ].map((section, index) => (
            <section key={index} className="text-gray-700">
              <h2 className="text-xl font-semibold text-gray-900 mb-2">
                {section.title}
              </h2>
              <p className="leading-relaxed">{section.content}</p>
            </section>
          ))}
        </div>

        {/* Closing */}
      </div>
    </div>
  );
};

export default UseServices;
